### ISSUE TITLE
OPEN ISSUE 3: Phase 3 - Post-Election Analysis

### ISSUE THREAD

**Issue by moby** [Voter-Aid/voteraid#3]
thinking of using http://www.highcharts.com/maps/demo/us-counties to create a live heatmap of incidents per election

**Comment by TheAlmightyBob** [comment]
https://public.tableau.com/ could be used for more interactive data exploration/analysis.
But it might take more time to set up and be less-flashy than highcharts.

(and perhaps the nature of this data might mean not wanting to make it too explorable)
